kakeibo/src/kakeibo/Controllers/KindsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using kakeibo.Data;
using kakeibo.Models.KakeiboModels;

namespace kakeibo.Controllers {
    public class KindsController : Controller {
        private readonly ApplicationDbContext _context;

        public KindsController(ApplicationDbContext context) {
            _context = context;
        }

        // GET: Kinds
        public async Task<IActionResult> Index() {
            var applicationDbContext = _context.Kind.UserFilter(this.User).Include(k => k.ApplicationUser).Include(k => k.KindParent);
            return View(applicationDbContext.ToList().SortEx());
        }


        // GET: Kinds/Create
        public IActionResult Create() {
            ViewData["KindId"] = new SelectList(_context.Kind.UserFilter(this.User).ToList().SortEx(), "Id", "Short");
            return View();
        }

        // POST: Kinds/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ApplicationUserId,KindId,Memo,Name,Short,Sort")] Kind kind) {
            if (ModelState.IsValid) {
                if (!this.User.IsInRole(KkConst.Role.Admin)) {
                    kind.ApplicationUserId = this.User.GetUserId();
                }
                // TODO:循環参照検知
                _context.Add(kind);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["KindId"] = new SelectList(_context.Kind.UserFilter(this.User).ToList().SortEx(), "Id", "Short", kind.KindId);
            return View(kind);
        }

        // GET: Kinds/Edit/5DDS
        public async Task<IActionResult> Edit(long? id) {
            if (id == null) {
                return NotFound();
            }

            var kind = await _context.Kind.UserFilter(this.User).SingleOrDefaultAsync(m => m.Id == id);
            if (kind == null) {
                return NotFound();
            }
            ViewData["KindId"] = new SelectList(_context.Kind.UserFilter(this.User).ToList().SortEx(), "Id", "Short", kind.KindId);
            return View(kind);
        }

        // POST: Kinds/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,ApplicationUserId,KindId,Memo,Name,Short,Sort")] Kind kind) {
            if (id != kind.Id) {
                return NotFound();
            }

            if (ModelState.IsValid) {
                try {
                    _context.Update(kind);
                    await _context.SaveChangesAsync();
                } catch (DbUpdateConcurrencyException) {
                    if (!KindExists(kind.Id)) {
                        return NotFound();
                    } else {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["KindId"] = new SelectList(_context.Kind.UserFilter(this.User).ToList().SortEx(), "Id", "Short", kind.KindId);
            return View(kind);
        }

        // GET: Kinds/Delete/5
        public async Task<IActionResult> Delete(long? id) {
            if (id == null) {
                return NotFound();
            }
            var kind = await _context.Kind.UserFilter(this.User).SingleOrDefaultAsync(m => m.Id == id);
            _context.Kind.Remove(kind);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool KindExists(long id) {
            return _context.Kind.UserFilter(this.User).Any(e => e.Id == id);
        }
    }
}

kakeibo/src/kakeibo/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using kakeibo.Data;
using kakeibo.Models.KakeiboModels;

namespace kakeibo.Controllers
{
    public class LocationsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LocationsController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Locations
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Location.UserFilter(this.User).Include(l => l.ApplicationUser).Include(l => l.Coordinate).Include(l => l.LocationParent).Include(l => l.PhotoGroup);
            return View(applicationDbContext.ToList().SortEx());
        }


        // GET: Locations/Create
        public IActionResult Create()
        {
            ViewData["CoordinateId"] = new SelectList(_context.Coordinate, "Id", "Id");
            ViewData["LocationId"] = new SelectList(_context.Location.UserFilter(this.User).ToList().SortEx(), "Id", "Short");
            ViewData["PhotoGroupId"] = new SelectList(_context.PhotoGroup, "Id", "Id");
            return View();
        }

        // POST: Locations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ApplicationUserId,CoordinateId,LocationId,Memo,Name,PhotoGroupId,Short,Sort")] Location location)
        {
            if (ModelState.IsValid)
            {
                if (!this.User.IsInRole(KkConst.Role.Admin)) {
                    location.ApplicationUserId = this.User.GetUserId();
                }
                _context.Add(location);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["CoordinateId"] = new SelectList(_context.Coordinate, "Id", "Id", location.CoordinateId);
            ViewData["LocationId"] = new SelectList(_context.Location.UserFilter(this.User).ToList().SortEx(), "Id", "Short", location.LocationId);
            ViewData["PhotoGroupId"] = new SelectList(_context.PhotoGroup, "Id", "Id", location.PhotoGroupId);
            return View(location);
        }

        // GET: Locations/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var location = await _context.Location.UserFilter(this.User).SingleOrDefaultAsync(m => m.Id == id);
            if (location == null)
            {
                return NotFound();
            }
            ViewData["CoordinateId"] = new SelectList(_context.Coordinate, "Id", "Id", location.CoordinateId);
            ViewData["LocationId"] = new SelectList(_context.Location.UserFilter(this.User).ToList().SortEx(), "Id", "Short", location.LocationId);
            ViewData["PhotoGroupId"] = new SelectList(_context.PhotoGroup, "Id", "Id", location.PhotoGroupId);
            return View(location);
        }

        // POST: Locations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,ApplicationUserId,CoordinateId,LocationId,Memo,Name,PhotoGroupId,Short,Sort")] Location location)
        {
            if (id != location.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(location);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LocationExists(location.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["CoordinateId"] = new SelectList(_context.Coordinate, "Id", "Id", location.CoordinateId);
            ViewData["LocationId"] = new SelectList(_context.Location.UserFilter(this.User).ToList().SortEx(), "Id", "Short", location.LocationId);
            ViewData["PhotoGroupId"] = new SelectList(_context.PhotoGroup, "Id", "Id", location.PhotoGroupId);
            return View(location);
        }

        // GET: Locations/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null) {
                return NotFound();
            }
            var location = await _context.Location.UserFilter(this.User).SingleOrDefaultAsync(m => m.Id == id);
            _context.Location.Remove(location);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool LocationExists(long id)
        {
            return _context.Location.UserFilter(this.User).Any(e => e.Id == id);
        }
    }
}

kakeibo/src/kakeibo/Controllers/PaymentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using kakeibo.Data;
using kakeibo.Models.KakeiboModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;

namespace kakeibo.Controllers {
    public class PaymentsController : Controller {
        private readonly ApplicationDbContext _context;

        public PaymentsController(ApplicationDbContext context) {
            _context = context;
        }

        // GET: Payments
        public async Task<IActionResult> Index() {
            var applicationDbContext = _context.Payment.UserFilter(this.User).Include(p => p.ApplicationUser);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Payments/Create
        public IActionResult Create() {
            return View();
        }

        // POST: Payments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Memo,Name,Short,Sort")] Payment payment) {
            if (ModelState.IsValid) {
                if (!this.User.IsInRole(KkConst.Role.Admin)) {
                    payment.ApplicationUserId = this.User.GetUserId();
                }
                _context.Add(payment);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(payment);
        }

        // GET: Payments/Edit/5
        public async Task<IActionResult> Edit(long? id) {
            if (id == null) {
                return NotFound();
            }

            var payment = await _context.Payment.UserFilter(this.User).SingleOrDefaultAsync(m => m.Id == id);
            if (payment == null) {
                return NotFound();
            }
            return View(payment);
        }

        // POST: Payments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,ApplicationUserId,Memo,Name,Short,Sort")] Payment payment) {
            if (id != payment.Id) {
                return NotFound();
            }

            if (ModelState.IsValid) {
                try {
                    _context.Update(payment);
                    await _context.SaveChangesAsync();
                } catch (DbUpdateConcurrencyException) {
                    if (!PaymentExists(payment.Id)) {
                        return NotFound();
                    } else {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(payment);
        }

        // GET: Payments/Delete/5
        public async Task<IActionResult> Delete(long? id) {
            if (id == null) {
                return NotFound();
            }
            var payment = await _context.Payment.UserFilter(this.User).SingleOrDefaultAsync(m => m.Id == id);
            _context.Payment.Remove(payment);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool PaymentExists(long id) {
            return _context.Payment.UserFilter(this.User).Any(e => e.Id == id);
        }
    }
}

kakeibo/src/kakeibo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>家計管理システム:@ViewData["Title"]</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">家計簿</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-left">
                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="Index">ホーム<span class="glyphicon glyphicon-home" /></a>
                    </li>
                    <li>
                        <a href="dropdown-toggle" data-toggle="dropdown">
                            入力
                            <span class="glyphicon glyphicon-pencil" />
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="#">出費</a></li>
                            <li><a href="#">予算</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="dropdown-toggle" data-toggle="dropdown">
                            分析
                            <span class="glyphicon glyphicon-search" />
                            <span class="caret" />
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="#">時間帯</a></li>
                            <li><a href="#">日別</a></li>
                            <li><a href="#">集計</a></li>
                            <li><a href="#">位置</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="dropdown-toggle" data-toggle="dropdown">
                            マスタ
                            <span class="glyphicon glyphicon-wrench" />
                            <span class="caret" />
                        </a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Locations" asp-action="Index">購入場所</a></li>
                            <li><a asp-area="" asp-controller="Payments" asp-action="Index">決済方法</a></li>
                            <li><a asp-area="" asp-controller="Kinds" asp-action="Index">商品分類</a></li>
                        </ul>
                    </li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <br />
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - 家計管理システム</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>